"""emai_schema

Revision ID: 6764cf66f538
Revises: 2d3a519e036b
Create Date: 2026-04-22 07:43:00.230010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6764cf66f538'
down_revision: Union[str, Sequence[str], None] = '2d3a519e036b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    op.drop_table('skills')
    op.drop_table('application_preferences')
    op.drop_table('projects')
    op.drop_table('education')
    op.drop_table('job_applications')
    op.drop_column('profiles', 'resume_path')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expire')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    op.add_column('profiles', sa.Column('resume_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_applications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_applications_pkey'))
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_of_study', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('education_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('education_pkey'))
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_table('application_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_ethnicity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('veteran_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disability_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authorized_to_work', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_sponsorship', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notice_period', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('application_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('application_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('application_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proficiency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skills_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_table('experience',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('experience_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experience_pkey'))
    )
    # ### end Alembic commands ###
