"""initial db

Revision ID: 6e06b945272d
Revises: 
Create Date: 2026-04-23 12:40:39.964880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e06b945272d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'last_name')
    op.drop_index(op.f('ix_user_refresh_tokens_token_jti'), table_name='user_refresh_tokens')
    op.create_index(op.f('ix_user_refresh_tokens_token_jti'), 'user_refresh_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_token_jti'), table_name='user_refresh_tokens')
    op.create_index(op.f('ix_user_refresh_tokens_token_jti'), 'user_refresh_tokens', ['token_jti'], unique=False)
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
